### ISSUE TITLE
Crash: java.lang.NoSuchMethodError: No virtual method addNetworkExtrasBundle(Ljava/lang/Class;Landroid/os/Bundle;)

### ISSUE THREAD

**Issue by tracer8** [AppLovin/AppLovin-MAX-SDK-Android#637]
### MAX SDK Version

12.3.1

### Device/Platform Info

Any device

### Current Behavior

Crash with this error when show Collapsible Banner of Google ads, use MAX SDK and Google Mobile Ads together:
`java.lang.NoSuchMethodError: No virtual method addNetworkExtrasBundle(Ljava/lang/Class;Landroid/os/Bundle;)Lcom/google/android/gms/ads/AbstractAdRequestBuilder; in class Lcom/google/android/gms/ads/AdRequest$Builder; or its super classes (declaration of 'com.google.android.gms.ads.AdRequest$Builder'`

### Expected Behavior

On version 12.3.0, Collapsible Banner of Google Ads will show success without any issue.

### How to Reproduce

Gradle:

    implementation 'com.applovin:applovin-sdk:12.3.1'
    implementation 'com.applovin.mediation:google-adapter:+'

I am use MAX and Google ads together, Google Mobile Ads to show Collapsible banner. Before version 12.3.1, everything is good, but after upgrade to 12.3.1, the error cause of crash show up "java.lang.NoSuchMethodError: No virtual method addNetworkExtrasBundle"

You can try to show GMA collapsible with this code try on both version to see the error

```
MobileAds.initialize(context, new OnInitializationCompleteListener() {
            @Override
            public void onInitializationComplete(InitializationStatus initializationStatus) {
            }
        });


private AdView mAdView;
    public void LoadBanner(Activity activity, ViewGroup container) {
        Log.d("ADMOB", "Try to load banner");
        this.mAdView = new AdView(activity);
        this.mAdView.setAdSize(this.getAdSize(activity, container));
        this.mAdView.setAdUnitId("ca-app-pub-3940256099942544/8388050270"); // test id already
        container.removeAllViews();
        container.setVisibility(View.VISIBLE);
        container.addView(this.mAdView);
        Bundle extras = new Bundle();
        extras.putString("collapsible", "bottom");
        AdRequest adRequest = ((AdRequest.Builder)(new AdRequest.Builder()).addNetworkExtrasBundle(AdMobAdapter.class, extras)).build();
        this.mAdView.loadAd(adRequest);
        this.mAdView.setAdListener(new AdListener() {
            public void onAdClicked() {
            }

            public void onAdClosed() {
            }

            public void onAdFailedToLoad(LoadAdError adError) {
                Log.d("ADMOB", "Banner fail to load: " + adError);
            }

            public void onAdImpression() {
                Log.d("ADMOB", "Banner impression");
            }

            public void onAdLoaded() {
                Log.d("ADMOB", "Banner loaded");
            }

            public void onAdOpened() {
            }
        });
    }

    private AdSize getAdSize(Activity activity, View adContainerView) {
        Display display = activity.getWindowManager().getDefaultDisplay();
        DisplayMetrics outMetrics = new DisplayMetrics();
        display.getMetrics(outMetrics);
        float widthPixels = (float)outMetrics.widthPixels;
        float density = outMetrics.density;
        int adWidth = (int)(widthPixels / density);
        return AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(activity, adWidth);
    }
```

**Comment by thomasmso** [comment]
@tracer8 - This is likely a mismatch of AdMob adapter and SDK version. Could you send a screenshot of the [Mediation Debugger](https://dash.applovin.com/documentation/mediation/android/testing-networks/mediation-debugger#sharing-the-mediation-debugger) so we can check that?

**Comment by tracer8** [comment]
![Screenshot_2024-03-20 11 31 50_001](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/15725821/0e26360f-b4bf-45b3-bbce-0c0534706a09)
Here is my adapters

**Comment by thomasmso** [comment]
And are you able to reproduce this locally when forcing AdMob live or test ads?

**Comment by tracer8** [comment]
> And are you able to reproduce this locally when forcing AdMob live or test ads?

yes, i can show admob with applovin MAX , but if show collapsible banner, it crashed.
I check the code, the method missing is still there. Can't understand why. May be cache of gradle or something?

**Comment by thomasmso** [comment]
That is strange, and not something we've had reported before. I am pretty sure it has something to do with your local environment, and +1 to your belief that it may have something to do with your local Gradle setup/cache. Unfortunately, there's not much we can do here unless we have access to your project / local environment. If you can reproduce it in a new app (e.g. our demo app), that would help as well.

**Comment by Jun19** [comment]
I also encountered the same problem 
Also using a mixture of max and admob
https://github.com/googleads/googleads-mobile-android-examples/issues/659

**Comment by lucasaue** [comment]
Hi @tracer8 ,

I had a similar problem and after weeks of investigation, I could find the cause and fix it.

The problem is caused by "[desugaring](https://developer.android.com/studio/write/java8-support)", which "moves things around." In particular, if you run dexdump classes.dex on the classes.dex contained within the .apk, you will find that all interfaces with static methods was splited in two, like `NameInterface` and `NameInterface$-CC`, where the `CC` splited interface contains all the statics methods.

`NameInterface$-CC` is not a interface present within the original classes.jar. Equally important, our code is looking for the create method on `NameInterface`, not `NameInterface$-CC`;, and while `NameInterface` exists in classes.dex, it does not contain the static create method.

This is why the `Java.Lang.NoSuchMethodError` is thrown.

Disabling desugar allow the app to run, but requires -- as you note in step (2) -- that the Minimum Android version to API Level be 24 or higher.

In my case, I just updated my minSDKVersion to 24 and fixed the problem.
