### ISSUE TITLE
error: incompatible types: int cannot be converted to String

### ISSUE THREAD

**Issue by jleprinc** [AppLovin/AppLovin-MAX-SDK-Android#538]
### MAX SDK Version

5.7.0

### Device/Platform Info

Android

### Current Behavior

Can't build android dependency 11.11.3

```
node_modules/react-native-applovin-max/android/src/main/java/com/applovin/reactnative/AppLovinMAXModule.java:2449: error: incompatible types: int cannot be converted to String
            errInfo.putString( "mediatedNetworkErrorCode", error.getMediatedNetworkErrorCode() );

node_modules/react-native-applovin-max/android/src/main/java/com/applovin/reactnative/AppLovinMAXModule.java:2467: error: incompatible types: int cannot be converted to String
        info.putString( "mediatedNetworkErrorCode", error.getMediatedNetworkErrorCode() );
```
                                                                                     ^

### How to Reproduce

Build on android with the version 5.7.0

**Comment by thomasmso** [comment]
Fixed in 5.7.1: https://github.com/AppLovin/AppLovin-MAX-React-Native/releases/tag/release_5_7_1

**Comment by thomasmso** [comment]
For future reference @jleprinc - Please file the issue in the correct repository.
